<%@ page language="java" contentType="text/html; charset=utf-8"
    pageEncoding="utf-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<dl>
	<dt>报告卡管理</dt>
	<dd>管理已有报告卡</dd>
	<dd>新增报告卡</dd>
</dl>
<dl>
	<dt>传染病管理</dt>
	<dd>管理已有传染病</dd>
	<dd>新增传染病</dd>
</dl>
<dl>
	<dt>传染病种类管理</dt>
	<dd>管理已有传染病种类</dd>
	<dd>新增传染病种类</dd>
</dl>
<dl>
	<dt>学校管理</dt>
	<dd>管理已有学校</dd>
	<dd>新增学校</dd>
	<dd>日常管理</dd>
	<dd>管理架构</dd>
</dl>
<dl>
	<dt>统计分析</dt>
	<dd>分年龄统计</dd>
	<dd>分学校统计</dd>
	<!--<dd>分人群统计</dd>
	<dd>分年龄实时统计</dd>
	<dd>分学校实时统计</dd>
	<dd>分人群实时统计</dd>-->
	<dd>分时间段统计饼状图</dd>
	<dd>分时间段统计柱状图</dd>
	<dd>分时间段统计折线图</dd>
</dl>
<dl>
	<dt>传染病防控知识</dt>
	<dd>传染病防控知识</dd>
</dl>